/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-01 18:14:47 UTC)
 * on 2014-04-04 at 08:05:00 UTC 
 * Modify at your own risk.
 */

package com.appspot.hk_taxi.anyTaxi.model;

/**
 * Model definition for Transaction.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the anyTaxi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Transaction extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cursor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String customerEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GeoPt customerLoc;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String customerLocStr;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GeoPt destLoc;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String destLocStr;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String driverEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GeoPt driverLoc;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numDriverNotified;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCursor() {
    return cursor;
  }

  /**
   * @param cursor cursor or {@code null} for none
   */
  public Transaction setCursor(java.lang.String cursor) {
    this.cursor = cursor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCustomerEmail() {
    return customerEmail;
  }

  /**
   * @param customerEmail customerEmail or {@code null} for none
   */
  public Transaction setCustomerEmail(java.lang.String customerEmail) {
    this.customerEmail = customerEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public GeoPt getCustomerLoc() {
    return customerLoc;
  }

  /**
   * @param customerLoc customerLoc or {@code null} for none
   */
  public Transaction setCustomerLoc(GeoPt customerLoc) {
    this.customerLoc = customerLoc;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCustomerLocStr() {
    return customerLocStr;
  }

  /**
   * @param customerLocStr customerLocStr or {@code null} for none
   */
  public Transaction setCustomerLocStr(java.lang.String customerLocStr) {
    this.customerLocStr = customerLocStr;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public GeoPt getDestLoc() {
    return destLoc;
  }

  /**
   * @param destLoc destLoc or {@code null} for none
   */
  public Transaction setDestLoc(GeoPt destLoc) {
    this.destLoc = destLoc;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDestLocStr() {
    return destLocStr;
  }

  /**
   * @param destLocStr destLocStr or {@code null} for none
   */
  public Transaction setDestLocStr(java.lang.String destLocStr) {
    this.destLocStr = destLocStr;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDriverEmail() {
    return driverEmail;
  }

  /**
   * @param driverEmail driverEmail or {@code null} for none
   */
  public Transaction setDriverEmail(java.lang.String driverEmail) {
    this.driverEmail = driverEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public GeoPt getDriverLoc() {
    return driverLoc;
  }

  /**
   * @param driverLoc driverLoc or {@code null} for none
   */
  public Transaction setDriverLoc(GeoPt driverLoc) {
    this.driverLoc = driverLoc;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Transaction setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumDriverNotified() {
    return numDriverNotified;
  }

  /**
   * @param numDriverNotified numDriverNotified or {@code null} for none
   */
  public Transaction setNumDriverNotified(java.lang.Integer numDriverNotified) {
    this.numDriverNotified = numDriverNotified;
    return this;
  }

  @Override
  public Transaction set(String fieldName, Object value) {
    return (Transaction) super.set(fieldName, value);
  }

  @Override
  public Transaction clone() {
    return (Transaction) super.clone();
  }

}
